### ISSUE TITLE
(chore) Define <title> and <meta> tags 

### ISSUE THREAD

**Issue by sfount** [IMA-WorldHealth/IMA-WorldHealth.github.io#2]
1. Adding a `<title>` tag will let the site be correctly displayed in Google searches as well as in the tab in users browsers
2. Meta tags will help indexing services like Google rank it correctly

**Comment by jniles** [comment]
@mbayopanda has provided me with some FR translations ... I'll add those in and fix this at the same time.

Got advice on meta tags?  I've heard they've fallen out of fashion.
